name: $(Rev:r)
pool: AGP-Linux
trigger: none

resources:
  repositories:
  - repository: airflow-dev
    type: git
    ref: dev
    name: k8s-airflow-dags
  - repository: airflow-prod
    type: git
    ref: prod
    name: k8s-airflow-dags
  pipelines:
    - pipeline: build
      source: crm-vuon-dados-clientes-build
      trigger:
        branches:
          include:
            - master 

stages:
  - stage: deploy_crm_vuon_dados_clientes_dev
    displayName: Deploy DEV K8s crm-vuon-dados-clientes
    dependsOn: []
    jobs:
    - deployment: deploy_crm_vuon_dados_clientes_airflow_dev
      displayName: Deploy DEV K8s crm-vuon-dados-clientes
      environment: crm-vuon-airflow-dev
      workspace:
        clean: true
      variables:
      - group: crm-vuon-airflow-dev
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: airflow-dev
              fetchDepth: 1
              persistCredentials: true
              path: airflow-dev
            - script: |
                set -e
                cp -r $(Pipeline.Workspace)/build/crm_vuon_dados_clientes/* $(Pipeline.Workspace)/airflow-dev/
                cd $(Pipeline.Workspace)/airflow-dev/
                git config user.email "dsv.inovacao@grpereira.com.br"
                git config user.name "azure devops pipeline"
                git add .
                git commit -m "crm_vuon_dados_clientes $(Build.BuildNumber)"
                git push origin HEAD:dev
              displayName: atualiza dags airflow dev

  - stage: deploy_crm_vuon_dados_clientes_prod
    displayName: Deploy Prod K8s crm-vuon-dados-clientes
    dependsOn: [deploy_crm_vuon_dados_clientes_dev]
    jobs:
    - deployment: deploy_crm_vuon_dados_clientes_airflow_prod
      displayName: Deploy Prod K8s crm-vuon-dados-clientes
      environment: crm-vuon-airflow-prod
      workspace:
        clean: true
      variables:
      - group: crm-vuon-airflow-prod
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: airflow-prod
              fetchDepth: 1
              persistCredentials: true
              path: airflow-prod
            - script: |
                set -e
                cp -r $(Pipeline.Workspace)/build/crm_vuon_dados_clientes/* $(Pipeline.Workspace)/airflow-prod/
                cd $(Pipeline.Workspace)/airflow-prod/
                git config user.email "dsv.inovacao@grpereira.com.br"
                git config user.name "azure devops pipeline"
                git add .
                git commit -m "crm_vuon_dados_clientes $(Build.BuildNumber)"
                git push origin HEAD:prod
              displayName: atualiza dags airflow prod